### ISSUE TITLE
Build from source on Apple Silicon: march=native not supported

### ISSUE THREAD

**Issue by CharlelieLrt** [nv-legate/legate.core#904]
I am trying to build legate locally from source on a M1 Macbook Pro (Apple Silicon), following the instructions given in the [BUILD.md](https://github.com/nv-legate/legate.core/blob/HEAD/BUILD.md#dependency-listing)
OS: MacOS 12.6.7
Dependencies are pulled with conda with the following environment config (generated with `./generate-conda-envs.py --python 3.10 --os osx`):

```yaml
name: legate-test
channels:
  - conda-forge
  - nvidia
dependencies:

  - python=3.10,!=3.9.7  # avoid https://bugs.python.org/issue45121

  # build
  - cmake>=3.24,!=3.25.0
  - cython
  - git
  - make
  - ninja
  - numba
  - openssl
  - pkg-config
  - rust
  - scikit-build>=0.13.1
  - setuptools>=60
  - zlib

  # runtime
  - cffi
  - llvm-openmp
  - numpy>=1.22
  - libblas=*=*openblas*
  - openblas=*=*openmp*
  - openblas<=0.3.21
  - opt_einsum
  - scipy
  - typing_extensions

  # tests
  - clang-tools>=8
  - clang>=8
  - colorama
  - coverage
  - mock
  - mypy>=0.961
  - pre-commit
  - pytest-cov
  - pytest-lazy-fixture
  - pytest-mock
  - pytest
  - types-docutils
  - pynvml
  - tifffile

  # docs
  - pandoc
  - doxygen
  - ipython
  - jinja2
  - markdown<3.4.0
  - pydata-sphinx-theme>=0.13
  - myst-parser
  - nbsphinx
  - sphinx-copybutton
  - sphinx>=4.4.0
```

Legate is built with `./install.py --max-dim 5 --openmp --hdf5 --build-tests --build-examples`, which fails with the following error:

```console
 Not searching for unused variables given on the command line.
 -- The C compiler identification is AppleClang 14.0.0.14000029
 -- The CXX compiler identification is AppleClang 14.0.0.14000029
 -- Detecting C compiler ABI info
 -- Detecting C compiler ABI info - done
 -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
 -- Detecting C compile features
 -- Detecting C compile features - done
 -- Detecting CXX compiler ABI info
 -- Detecting CXX compiler ABI info - done
 -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
 -- Detecting CXX compile features
 -- Detecting CXX compile features - done
 -- Found Git: /Users/charlelie/anaconda3/envs/legate/bin/git (found version "2.43.0")
 -- Found Python3: /Users/charlelie/anaconda3/envs/legate/bin/python3 (found version "3.10.13") found components: Interpreter Development Development.Module Development.Embed
 -- CPM: adding package Legion@24.1.0 (24.1.0)
 -- Performing Test COMPILER_SUPPORTS_MARCH
 -- Performing Test COMPILER_SUPPORTS_MARCH - Failed
 CMake Error at _skbuild/macosx-12.0-arm64-3.10/cmake-build/_deps/legion-src/CMakeLists.txt:145 (message):
   The flag -march=native is not supported by the compiler
```
