### ISSUE TITLE
Build from source on PowerPC 9: no cuda-version package

### ISSUE THREAD

**Issue by CharlelieLrt** [nv-legate/legate.core#905]
I am trying to build legate from source on Lassen (PowerPC9, OS: RHEL 7.9 Maipo) following instructions in the [quickstart](https://github.com/nv-legate/quickstart#create-a-conda-environment).

I generate a config file for my conda environment with `./scripts/generate-conda-envs.py --python 3.10 --ctk 11.8 --os linux`. The config file is:

```yaml
name: legate-test
channels:
  - conda-forge
  - nvidia
dependencies:

  - python=3.10,!=3.9.7  # avoid https://bugs.python.org/issue45121

  # cuda
  - cuda-version=11.8
  - cutensor>=1.3.3,<2
  - nccl
  - pynvml

  # build
  - cmake>=3.24,!=3.25.0
  - cython
  - elfutils
  - git
  - make
  - ninja
  - numba
  - openssl
  - pkg-config
  - rust
  - scikit-build>=0.13.1
  - setuptools>=60
  - zlib

  # runtime
  - cffi
  - llvm-openmp
  - numpy>=1.22
  - libblas=*=*openblas*
  - openblas=*=*openmp*
  - openblas<=0.3.21
  - opt_einsum
  - scipy
  - typing_extensions

  # tests
  - clang-tools>=8
  - clang>=8
  - colorama
  - coverage
  - mock
  - mypy>=0.961
  - pre-commit
  - pytest-cov
  - pytest-lazy-fixture
  - pytest-mock
  - pytest
  - types-docutils
  - pynvml
  - tifffile

  # docs
  - pandoc
  - doxygen
  - ipython
  - jinja2
  - markdown<3.4.0
  - pydata-sphinx-theme>=0.13
  - myst-parser
  - nbsphinx
  - sphinx-copybutton
  - sphinx>=4.4.0
```

Trying to create the environmnet gives the following error:

```console
ResolvePackageNotFound: 
  - pydata-sphinx-theme[version='>=0.13']
  - cuda-version=11.8
```

In addition, running `conda search cuda-version -c nvidia -c conda-forge` suggests that the `cuda-version` package does not exist in these channels.
```
